# Generated by Django 4.2.6 on 2023-10-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='banner_title',
            field=models.CharField(default='Welcome to my Genericpage', max_length=100),
        ),
    ]
