# Generated by Django 4.2.6 on 2023-10-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_alter_genericpage_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
