# Generated by Django 4.2.6 on 2023-10-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0010_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutussection',
            name='about_us_carousel_images',
            field=models.ManyToManyField(blank=True, to='wagtailimages.image'),
        ),
    ]
