# Generated by Django 4.2.6 on 2023-11-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_aboutussection_about_us_carousel_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutussection',
            name='about_us_carousel_images',
        ),
    ]
